
// This file is autogenerated
#ifndef GLOBAL_REVISION_H_
#define GLOBAL_REVISION_H_


namespace global {

static constexpr const char* ALIAS_REVISION = "cd02ba572f35e7dfef6e57293e634ce8dda2df2c";

}


#endif // GLOBAL_REVISION_H_


