#!/bin/bash

# will exit bash if a command doesnt succeed
set -e
. $(dirname "$0")/env_vars.sh


REVISION_VERSION=$(git rev-parse HEAD)

echo "Revision hash: $REVISION_VERSION"

FILE_CONTENT="
// This file is autogenerated
#ifndef GLOBAL_REVISION_H_
#define GLOBAL_REVISION_H_


namespace global {

static constexpr const char* ALIAS_REVISION = \"$REVISION_VERSION\";

}


#endif // GLOBAL_REVISION_H_

"

OUTPUT_FILE=$ROOT_REPO_DIR/src/global/include/global/revision.h

echo "$FILE_CONTENT" > "$OUTPUT_FILE"